# Gera automaticamente o script do banco de dados
#spring:
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          delimiter: ;
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql

---

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    use-legacy-processing: true
    activate:
      on-profile: dev

---

spring:
  cache:
    type: redis
    redis:
      cache-null-values: false

  redis:
    host: localhost
    password:
    port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/easyong
    username: postgres
    password: postgres
    splatform: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    open-in-view: true
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:hello}
    password: ${MAIL_PASSWORD:hello}

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
#
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#          starttls:
#            enable: true
