server:
  port: ${PORT}
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    use-legacy-processing: true
    activate:
      on-profile: prod

---

 spring:
  redis.url: ${REDIS_URL}

  datasource:
    url: ${DATABASE_URL}
    initialization-mode: never

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${EMAIL_HOST:smtp.mailtrap.io}
    port: ${EMAIL_PORT:2525}
    username: ${EMAIL_USERNAME:232046fdf175bc}
    password: ${EMAIL_PASSWORD:d5a2f3ecb3ff1a}

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000




