server:
  port: ${PORT}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

spring:
  config:
    use-legacy-processing: true
    activate:
      on-profile: prod

---

 spring:
  redis.url: ${REDIS_URL}

  datasource:
    url: ${DATABASE_URL}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${EMAIL_HOST:smtp.mailtrap.io}
    port: ${EMAIL_PORT:2525}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true