server:
  port: ${PORT}
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    use-legacy-processing: true
    activate:
      on-profile: prod

---

 spring:
  redis.url: ${REDIS_URL}

  datasource:
    url: ${DATABASE_URL}
    initialization-mode: never

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${EMAIL_HOST:smtp.mailtrap.io}
    port: ${EMAIL_PORT:2525}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
#
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#          starttls:
#            enable: true



