server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    use-legacy-processing: true
    activate:
      on-profile: test

---

spring:
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:25432/easyong
    username: postgres
    password: postgres
    initialization-mode: ALWAYS
    data: classpath:/database/initial-data.sql, classpath:/database/initial-data-dev.sql, classpath:/database/update-sequence.sql
  
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

